Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (1, '12', 'Acre', 'AC', 'Norte');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (2, '27', 'Alagoas', 'AL', 'Nordeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (3, '16', 'Amapá', 'AP', 'Norte');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (4, '13', 'Amazonas', 'AM', 'Norte');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (5, '29', 'Bahia', 'BA', 'Nordeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (6, '23', 'Ceará', 'CE', 'Nordeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (7, '53', 'Distrito Federal', 'DF', 'Centro-Oeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (8, '32', 'Espírito Santo', 'ES', 'Sudeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (9, '52', 'Goiás', 'GO', 'Centro-Oeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (10, '21', 'Maranhão', 'MA', 'Nordeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (11, '51', 'Mato Grosso', 'MT', 'Centro-Oeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (12, '50', 'Mato Grosso do Sul', 'MS', 'Centro-Oeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (13, '31', 'Minas Gerais', 'MG', 'Sudeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (14, '15', 'Pará', 'PA', 'Nordeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (15, '25', 'Paraíba', 'PB', 'Nordeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (16, '41', 'Paraná', 'PR', 'Sul');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (17, '26', 'Pernambuco', 'PE', 'Nordeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (18, '22', 'Piauí', 'PI', 'Nordeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (19, '33', 'Rio de Janeiro', 'RJ', 'Sudeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (20, '24', 'Rio Grande do Norte', 'RN', 'Nordeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (21, '43', 'Rio Grande do Sul', 'RS', 'Sul');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (22, '11', 'Rondônia', 'RO', 'Norte');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (23, '14', 'Roraima', 'RR', 'Norte');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (24, '42', 'Santa Catarina', 'SC', 'Sul');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (25, '35', 'São Paulo', 'SP', 'Sudeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (26, '28', 'Sergipe', 'SE', 'Nordeste');
Insert into Estado (id, codigo_ibge, nome, sigla, regiao) values (27, '17', 'Tocantins', 'TO', 'Norte');
