INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(1, 'Afeganistão', 'AF', 'AFG', '004');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(2, 'África do Sul', 'ZA', 'ZAF', '710');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(3, 'Albânia', 'AL', 'ALB', '008');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(4, 'Alemanha', 'DE', 'DEU', '276');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(5, 'Andorra', 'AD', 'AND', '020');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(6, 'Angola', 'AO', 'AGO', '024');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(7, 'Anguilla', 'AI', 'AIA', '660');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(8, 'Antártida', 'AQ', 'ATA', '010');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(9, 'Antígua e Barbuda', 'AG', 'ATG', '028');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(10, 'Antilhas Holandesas', 'AN', 'ANT', '530');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(11, 'Arábia Saudita', 'SA', 'SAU', '682');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(12, 'Argélia', 'DZ', 'DZA', '012');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(13, 'Argentina', 'AR', 'ARG', '032');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(14, 'Armênia', 'AM', 'ARM', '051');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(15, 'Aruba', 'AW', 'ABW', '533');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(16, 'Austrália', 'AU', 'AUS', '036');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(17, 'Áustria', 'AT', 'AUT', '040');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(18, 'Azerbaijão', 'AZ', 'AZE', '031');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(19, 'Bahamas', 'BS', 'BHS', '044');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(20, 'Bahrein', 'BH', 'BHR', '048');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(21, 'Bangladesh', 'BD', 'BGD', '050');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(22, 'Barbados', 'BB', 'BRB', '052');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(23, 'Belarus', 'BY', 'BLR', '112');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(24, 'Bélgica', 'BE', 'BEL', '056');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(25, 'Belize', 'BZ', 'BLZ', '084');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(26, 'Benin', 'BJ', 'BEN', '204');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(27, 'Bermudas', 'BM', 'BMU', '060');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(28, 'Bolívia', 'BO', 'BOL', '068');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(29, 'Bósnia-Herzegóvina', 'BA', 'BIH', '070');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(30, 'Botsuana', 'BW', 'BWA', '072');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(31, 'Brasil', 'BR', 'BRA', '076');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(32, 'Brunei', 'BN', 'BRN', '096');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(33, 'Bulgária', 'BG', 'BGR', '100');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(34, 'Burkina Fasso', 'BF', 'BFA', '854');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(35, 'Burundi', 'BI', 'BDI', '108');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(36, 'Butão', 'BT', 'BTN', '064');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(37, 'Cabo Verde', 'CV', 'CPV', '132');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(38, 'Camarões', 'CM', 'CMR', '120');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(39, 'Camboja', 'KH', 'KHM', '116');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(40, 'Canadá', 'CA', 'CAN', '124');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(41, 'Cazaquistão', 'KZ', 'KAZ', '398');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(42, 'Chade', 'TD', 'TCD', '148');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(43, 'Chile', 'CL', 'CHL', '152');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(44, 'China', 'CN', 'CHN', '156');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(45, 'Chipre', 'CY', 'CYP', '196');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(46, 'Cingapura', 'SG', 'SGP', '702');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(47, 'Colômbia', 'CO', 'COL', '170');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(48, 'Congo', 'CG', 'COG', '178');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(49, 'Coréia do Norte', 'KP', 'PRK', '408');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(50, 'Coréia do Sul', 'KR', 'KOR', '410');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(51, 'Costa do Marfim', 'CI', 'CIV', '384');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(52, 'Costa Rica', 'CR', 'CRI', '188');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(53, 'Croácia (Hrvatska)', 'HR', 'HRV', '191');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(54, 'Cuba', 'CU', 'CUB', '192');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(55, 'Dinamarca', 'DK', 'DNK', '208');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(56, 'Djibuti', 'DJ', 'DJI', '262');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(57, 'Dominica', 'DM', 'DMA', '212');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(58, 'Egito', 'EG', 'EGY', '818');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(59, 'El Salvador', 'SV', 'SLV', '222');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(60, 'Emirados Árabes Unidos', 'AE', 'ARE', '784');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(61, 'Equador', 'EC', 'ECU', '218');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(62, 'Eritréia', 'ER', 'ERI', '232');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(63, 'Eslováquia', 'SK', 'SVK', '703');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(64, 'Eslovênia', 'SI', 'SVN', '705');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(65, 'Espanha', 'ES', 'ESP', '724');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(66, 'Estados Unidos', 'US', 'USA', '840');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(67, 'Estônia', 'EE', 'EST', '233');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(68, 'Etiópia', 'ET', 'ETH', '231');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(69, 'Fiji', 'FJ', 'FJI', '242');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(70, 'Filipinas', 'PH', 'PHL', '608');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(71, 'Finlândia', 'FI', 'FIN', '246');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(72, 'França', 'FR', 'FRA', '250');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(73, 'Gabão', 'GA', 'GAB', '266');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(74, 'Gâmbia', 'GM', 'GMB', '270');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(75, 'Gana', 'GH', 'GHA', '288');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(76, 'Geórgia', 'GE', 'GEO', '268');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(77, 'Gibraltar', 'GI', 'GIB', '292');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(78, 'Grã-Bretanha (Reino Unido, UK)', 'GB', 'GBR', '826');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(79, 'Granada', 'GD', 'GRD', '308');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(80, 'Grécia', 'GR', 'GRC', '300');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(81, 'Groelândia', 'GL', 'GRL', '304');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(82, 'Guadalupe', 'GP', 'GLP', '312');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(83, 'Guam (Território dos Estados Unidos)', 'GU', 'GUM', '316');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(84, 'Guatemala', 'GT', 'GTM', '320');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(85, 'Guernsey', 'G', 'GGY', '832');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(86, 'Guiana', 'GY', 'GUY', '328');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(87, 'Guiana Francesa', 'GF', 'GUF', '254');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(88, 'Guiné', 'GN', 'GIN', '324');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(89, 'Guiné Equatorial', 'GQ', 'GNQ', '226');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(90, 'Guiné-Bissau', 'GW', 'GNB', '624');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(91, 'Haiti', 'HT', 'HTI', '332');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(92, 'Holanda', 'NL', 'NLD', '528');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(93, 'Honduras', 'HN', 'HND', '340');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(94, 'Hong Kong', 'HK', 'HKG', '344');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(95, 'Hungria', 'HU', 'HUN', '348');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(96, 'Iêmen', 'YE', 'YEM', '887');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(97, 'Ilha Bouvet (Território da Noruega)', 'BV', 'BVT', '074');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(98, 'Ilha do Homem', 'IM', 'IMN', '833');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(99, 'Ilha Natal', 'CX', 'CXR', '162');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(100, 'Ilha Pitcairn', 'PN', 'PCN', '612');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(101, 'Ilha Reunião', 'RE', 'REU', '638');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(102, 'Ilhas Aland', 'AX', 'ALA', '248');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(103, 'Ilhas Cayman', 'KY', 'CYM', '136');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(104, 'Ilhas Cocos', 'CC', 'CCK', '166');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(105, 'Ilhas Comores', 'KM', 'COM', '174');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(106, 'Ilhas Cook', 'CK', 'COK', '184');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(107, 'Ilhas Faroes', 'FO', 'FRO', '234');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(108, 'Ilhas Falkland (Malvinas)', 'FK', 'FLK', '238');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(109, 'Ilhas Geórgia do Sul e Sandwich do Sul', 'GS', 'SGS', '239');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(110, 'Ilhas Heard e McDonald (Território da Austrália)', 'HM', 'HMD', '334');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(111, 'Ilhas Marianas do Norte', 'MP', 'MNP', '580');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(112, 'Ilhas Marshall', 'MH', 'MHL', '584');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(113, 'Ilhas Menores dos Estados Unidos', 'UM', 'UMI', '581');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(114, 'Ilhas Norfolk', 'NF', 'NFK', '574');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(115, 'Ilhas Seychelles', 'SC', 'SYC', '690');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(116, 'Ilhas Solomão', 'SB', 'SLB', '090');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(117, 'Ilhas Svalbard e Jan Mayen', 'SJ', 'SJM', '744');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(118, 'Ilhas Tokelau', 'TK', 'TKL', '772');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(119, 'Ilhas Turks e Caicos', 'TC', 'TCA', '796');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(120, 'Ilhas Virgens (Estados Unidos)', 'VI', 'VIR', '850');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(121, 'Ilhas Virgens (Inglaterra)', 'VG', 'VGB', '092');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(122, 'Ilhas Wallis e Futuna', 'WF', 'WLF', '876');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(123, 'índia', 'IN', 'IND', '356');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(124, 'Indonésia', 'ID', 'IDN', '360');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(125, 'Irã', 'IR', 'IRN', '364');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(126, 'Iraque', 'IQ', 'IRQ', '368');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(127, 'Irlanda', 'IE', 'IRL', '372');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(128, 'Islândia', 'IS', 'ISL', '352');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(129, 'Israel', 'IL', 'ISR', '376');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(130, 'Itália', 'IT', 'ITA', '380');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(131, 'Jamaica', 'JM', 'JAM', '388');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(132, 'Japão', 'JP', 'JPN', '392');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(133, 'Jersey', 'JE', 'JEY', '832');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(134, 'Jordânia', 'JO', 'JOR', '400');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(135, 'Kênia', 'KE', 'KEN', '404');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(136, 'Kiribati', 'KI', 'KIR', '296');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(137, 'Kuait', 'KW', 'KWT', '414');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(138, 'Laos', 'LA', 'LAO', '418');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(139, 'Látvia', 'LV', 'LVA', '428');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(140, 'Lesoto', 'LS', 'LSO', '426');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(141, 'Líbano', 'LB', 'LBN', '422');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(142, 'Libéria', 'LR', 'LBR', '430');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(143, 'Líbia', 'LY', 'LBY', '434');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(144, 'Liechtenstein', 'LI', 'LIE', '438');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(145, 'Lituânia', 'LT', 'LTU', '440');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(146, 'Luxemburgo', 'LU', 'LUX', '442');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(147, 'Macau', 'MO', 'MAC', '446');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(148, 'Macedônia (República Yugoslava)', 'MK', 'MKD', '807');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(149, 'Madagascar', 'MG', 'MDG', '450');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(150, 'Malásia', 'MY', 'MYS', '458');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(151, 'Malaui', 'MW', 'MWI', '454');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(152, 'Maldivas', 'MV', 'MDV', '462');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(153, 'Mali', 'ML', 'MLI', '466');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(154, 'Malta', 'MT', 'MLT', '470');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(155, 'Marrocos', 'MA', 'MAR', '504');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(156, 'Martinica', 'MQ', 'MTQ', '474');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(157, 'Maurício', 'MU', 'MUS', '480');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(158, 'Mauritânia', 'MR', 'MRT', '478');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(159, 'Mayotte', 'YT', 'MYT', '175');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(160, 'México', 'MX', 'MEX', '484');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(161, 'Micronésia', 'FM', 'FSM', '583');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(162, 'Moçambique', 'MZ', 'MOZ', '508');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(163, 'Moldova', 'MD', 'MDA', '498');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(164, 'Mônaco', 'MC', 'MCO', '492');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(165, 'Mongólia', 'MN', 'MNG', '496');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(166, 'Montenegro', 'ME', 'MNE', '499');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(167, 'Montserrat', 'MS', 'MSR', '500');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(168, 'Myanma', 'MM', 'MMR', '104');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(169, 'Namíbia', 'NA', 'NAM', '516');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(170, 'Nauru', 'NR', 'NRU', '520');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(171, 'Nepal', 'NP', 'NPL', '524');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(172, 'Nicarágua', 'NI', 'NIC', '558');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(173, 'Níger', 'NE', 'NER', '562');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(174, 'Nigéria', 'NG', 'NGA', '566');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(175, 'Niue', 'NU', 'NIU', '570');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(176, 'Noruega', 'NO', 'NOR', '578');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(177, 'Nova Caledônia', 'NC', 'NCL', '540');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(178, 'Nova Zelândia', 'NZ', 'NZL', '554');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(179, 'Omã', 'OM', 'OMN', '512');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(180, 'Palau', 'PW', 'PLW', '585');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(181, 'Panamá', 'PA', 'PAN', '591');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(182, 'Papua-Nova Guiné', 'PG', 'PNG', '598');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(183, 'Paquistão', 'PK', 'PAK', '586');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(184, 'Paraguai', 'PY', 'PRY', '600');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(185, 'Peru', 'PE', 'PER', '604');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(186, 'Polinésia Francesa', 'PF', 'PYF', '258');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(187, 'Polônia', 'PL', 'POL', '616');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(188, 'Porto Rico', 'PR', 'PRI', '630');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(189, 'Portugal', 'PT', 'PRT', '620');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(190, 'Qatar', 'QA', 'QAT', '634');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(191, 'Quirguistão', 'KG', 'KGZ', '417');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(192, 'República Centro-Africana', 'CF', 'CAF', '140');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(193, 'República Democrática do Congo', 'CD', 'COD', '180');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(194, 'República Dominicana', 'DO', 'DOM', '214');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(195, 'República Tcheca', 'CZ', 'CZE', '203');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(196, 'Romênia', 'RO', 'ROM', '642');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(197, 'Ruanda', 'RW', 'RWA', '646');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(198, 'Rússia (antiga URSS) - Federação Russa', 'RU', 'RUS', '643');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(199, 'Saara Ocidental', 'EH', 'ESH', '732');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(200, 'Saint Vincente e Granadinas', 'VC', 'VCT', '670');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(201, 'Samoa Americana', 'AS', 'ASM', '016');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(202, 'Samoa Ocidental', 'WS', 'WSM', '882');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(203, 'San Marino', 'SM', 'SMR', '674');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(204, 'Santa Helena', 'SH', 'SHN', '654');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(205, 'Santa Lúcia', 'LC', 'LCA', '662');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(206, 'São Bartolomeu', 'BL', 'BLM', '652');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(207, 'São Cristóvão e Névis', 'KN', 'KNA', '659');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(208, 'São Martim', 'MF', 'MAF', '663');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(209, 'São Tomé e Príncipe', 'ST', 'STP', '678');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(210, 'Senegal', 'SN', 'SEN', '686');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(211, 'Serra Leoa', 'SL', 'SLE', '694');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(212, 'Sérvia', 'RS', 'SRB', '688');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(213, 'Síria', 'SY', 'SYR', '760');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(214, 'Somália', 'SO', 'SOM', '706');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(215, 'Sri Lanka', 'LK', 'LKA', '144');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(216, 'St. Pierre and Miquelon', 'PM', 'SPM', '666');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(217, 'Suazilândia', 'SZ', 'SWZ', '748');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(218, 'Sudão', 'SD', 'SDN', '736');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(219, 'Suécia', 'SE', 'SWE', '752');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(220, 'Suíça', 'CH', 'CHE', '756');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(221, 'Suriname', 'SR', 'SUR', '740');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(222, 'Tadjiquistão', 'TJ', 'TJK', '762');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(223, 'Tailândia', 'TH', 'THA', '764');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(224, 'Taiwan', 'TW', 'TWN', '158');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(225, 'Tanzânia', 'TZ', 'TZA', '834');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(226, 'Território Britânico do Oceano índico', 'IO', 'IOT', '086');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(227, 'Territórios do Sul da França', 'TF', 'ATF', '260');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(228, 'Territórios Palestinos Ocupados', 'PS', 'PSE', '275');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(229, 'Timor Leste', 'TP', 'TMP', '626');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(230, 'Togo', 'TG', 'TGO', '768');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(231, 'Tonga', 'TO', 'TON', '776');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(232, 'Trinidad and Tobago', 'TT', 'TTO', '780');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(233, 'Tunísia', 'TN', 'TUN', '788');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(234, 'Turcomenistão', 'TM', 'TKM', '795');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(235, 'Turquia', 'TR', 'TUR', '792');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(236, 'Tuvalu', 'TV', 'TUV', '798');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(237, 'Ucrânia', 'UA', 'UKR', '804');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(238, 'Uganda', 'UG', 'UGA', '800');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(239, 'Uruguai', 'UY', 'URY', '858');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(240, 'Uzbequistão', 'UZ', 'UZB', '860');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(241, 'Vanuatu', 'VU', 'VUT', '548');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(242, 'Vaticano', 'VA', 'VAT', '336');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(243, 'Venezuela', 'VE', 'VEN', '862');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(244, 'Vietnã', 'VN', 'VNM', '704');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(245, 'Zâmbia', 'ZM', 'ZMB', '894');
INSERT INTO pais (id, nome, sigla_dois, sigla_tres, codigo_iso) VALUES(246, 'Zimbábue', 'ZW', 'ZWE', '716');